if(NOT BUILD_ARM)
    message(STATUS "Building bfpp_acc_v1_driver for X86")
    
    add_library(bfpp_acc_v1_driver OBJECT acc_driver.h acc_container.h systemc_binding.h)
    set_target_properties(bfpp_acc_v1_driver PROPERTIES LINKER_LANGUAGE CXX)
    target_link_libraries(bfpp_acc_v1_driver PUBLIC bfpp_acc_v1 ${SECDA_TOOLS_SIM_LIBRARIES} ${SYSC_LIBRARIES})
    target_include_directories(bfpp_acc_v1_driver PUBLIC  ${SECDA_TOOLS_INCLUDES} ${SYSC_INCLUDES})
    if (ACC_PRELOAD)
        target_compile_definitions(bfpp_acc_v1_driver PUBLIC -DACC_PRELOAD)
    endif()
    target_compile_definitions(bfpp_acc_v1_driver PUBLIC ${SECDA_ACC_SUPPORT})

    add_library(bfpp_acc_v1_driver_connector OBJECT acc_driver_connector.h acc_driver_connector.cc)
    target_link_libraries(bfpp_acc_v1_driver_connector PUBLIC bfpp_acc_v1_driver)
    set_target_properties(bfpp_acc_v1_driver_connector PROPERTIES LINKER_LANGUAGE CXX)
    target_compile_options(bfpp_acc_v1_driver_connector PUBLIC -fPIC -DSYSC)

else()
    message(STATUS "Building bfpp_acc_v1_driver for ARM")

    add_library(bfpp_acc_v1_driver OBJECT acc_driver.h acc_container.h)
    set_target_properties(bfpp_acc_v1_driver PROPERTIES LINKER_LANGUAGE CXX)
    target_link_libraries(bfpp_acc_v1_driver PUBLIC bfpp_acc_v1 ${SECDA_TOOLS_LIBRARIES})
    target_include_directories(bfpp_acc_v1_driver PUBLIC  ${SECDA_TOOLS_INCLUDES})
    target_compile_options(bfpp_acc_v1_driver PUBLIC -fPIC)
    if (ACC_PRELOAD)
        target_compile_definitions(bfpp_acc_v1_driver PUBLIC -DACC_PRELOAD)
    endif()
    if (BUILD_KRIA)
        target_compile_definitions(bfpp_acc_v1_driver PUBLIC -DKRIA)
    endif()
    target_compile_definitions(bfpp_acc_v1_driver PUBLIC -DGGML_SECDA_ARM ${SECDA_ACC_SUPPORT})

    add_library(bfpp_acc_v1_driver_connector OBJECT acc_driver_connector.h acc_driver_connector.cc)
    target_link_libraries(bfpp_acc_v1_driver_connector PUBLIC bfpp_acc_v1_driver)
    set_target_properties(bfpp_acc_v1_driver_connector PROPERTIES LINKER_LANGUAGE CXX)
    target_compile_options(bfpp_acc_v1_driver_connector PUBLIC -fPIC)
endif()
