#ifndef ACC_SCHEDULE_H
#define ACC_SCHEDULE_H

// GENERATED by third_party/secda_core/hardware_automation/sched_sync.py.
// Do not edit: re-run sched_sync.py --apply after synthesis instead.
//
// Per-iteration loop cost taken from the HLS schedule, for use as DWAIT
// arguments so the SystemC simulation costs what the hardware does.
// Only the simulation reads these -- DWAIT is erased under __SYNTHESIS__.
//
// Each variant is listed separately because one accelerator source is
// synthesised for several boards, whose schedules need not agree.
// Select one with -DSECDA_HW_VARIANT_<variant>; without it, a board
// build gets that board's first variant and a board-less build the
// simulation default.

#if !defined(SECDA_HW_VARIANT_BFPP_ACCv4_0_KRIA)
#if defined(KRIA)
#define SECDA_HW_VARIANT_BFPP_ACCv4_0_KRIA
#else
// Simulation default: BFPP_ACCv4_0_KRIA (from BFPP_ACC_KRIA_4_0, 2026-09-30T00:33:35Z).
// The SystemC build defines no board, so it models this one.
#define SECDA_HW_VARIANT_BFPP_ACCv4_0_KRIA
#endif
#endif

#if defined(SECDA_HW_VARIANT_BFPP_ACCv4_0_KRIA)
// BFPP_ACCv4_0_KRIA, from BFPP_ACC_KRIA_4_0 (2026-09-30T00:33:35Z)
#define SCHED_BFPP_UNIT_Compute_L1 2 // bfp_processor_threads.sc.h:77 Loop 1
#define SCHED_BFPP_UNIT_Compute_L1_1 29 // bfp_processor_threads.sc.h:91 Loop 1.1
#define SCHED_BFPP_UNIT_Compute_L1_1_1 15 // bfp_processor_threads.sc.h:95 Loop 1.1.1
#define SCHED_BFPP_UNIT_LoadInputs_L1 2 // bfp_processor_threads.sc.h:32 Loop 1
#define SCHED_BFPP_UNIT_LoadInputs_L1_1 3 // bfp_processor_threads.sc.h:37 Loop 1.1
#define SCHED_BFPP_UNIT_LoadInputs_L1_1_1 1 // bfp_processor_threads.sc.h:44 Loop 1.1.1
#define SCHED_BFPP_UNIT_LoadInputs_L1_1_2 1 // bfp_processor_threads.sc.h:55 Loop 1.1.2
#define SCHED_BFPP_UNIT_LoadWeights_L1 2 // bfp_processor_threads.sc.h:11 Loop 1
#define SCHED_BFPP_UNIT_LoadWeights_loop_A 2 // bfp_processor_functions.sc.h:199 loop_A
#define SCHED_BFPP_UNIT_LoadWeights_loop_B 8 // bfp_processor_functions.sc.h:228 loop_B
#define SCHED_BFPP_UNIT_LoadWeights_loop_C 16 // bfp_processor_functions.sc.h:296 loop_C
#define SCHED_BFPP_UNIT_LoadWeights_loop_D 1 // bfp_processor_functions.sc.h:371 loop_D
#define SCHED_BFPP_UNIT_LoadWeights_loop_E 1 // bfp_processor_functions.sc.h:414 loop_E
#define SCHED_BFPP_UNIT_LoadWeights_loop_G 1 // bfp_processor_functions.sc.h:444 loop_G
#define SCHED_BFP_Acc_HW_MAIN_L1 1 // acc.sc.h:177 Loop 1
#define SCHED_BFP_Acc_Load_Unit_L1_1 1 // acc_load_unit.sc.h:175 Loop 1.1
#define SCHED_BFP_Acc_Scheduler_L1 7 // acc_scheduler.sc.h:46 Loop 1
#define SCHED_BFP_Acc_Softmax_Unit_L1_1 1 // acc_softmax_unit.sc.h:102 Loop 1.1
#define SCHED_BFP_Acc_Softmax_Unit_L1_2 1 // acc_softmax_unit.sc.h:111 Loop 1.2
#define SCHED_BFP_Acc_Softmax_Unit_L1_3 0 // acc_softmax_unit.sc.h:125 Loop 1.3
#define SCHED_BFP_Acc_Softmax_Unit_L1_4 5 // acc_softmax_unit.sc.h:133 Loop 1.4
#define SCHED_BFP_Acc_Softmax_Unit_L1_5 1 // acc_softmax_unit.sc.h:166 Loop 1.5
#define SCHED_BFP_Acc_Store_Unit_L1 1 // acc_store_unit.sc.h:13 Loop 1
#define SCHED_BFP_Acc_WeightLoader_A_L1 2 // acc_load_unit.sc.h:70 Loop 1
#define SCHED_BFP_Acc_WeightLoader_A_L1_1 1 // acc_load_unit.sc.h:72 Loop 1.1
#define SCHED_BFP_Acc_WeightLoader_B_L1 2 // acc_load_unit.sc.h:90 Loop 1
#define SCHED_BFP_Acc_WeightLoader_B_L1_1 1 // acc_load_unit.sc.h:92 Loop 1.1
#define SCHED_BFP_Acc_WeightLoader_C_L1 2 // acc_load_unit.sc.h:110 Loop 1
#define SCHED_BFP_Acc_WeightLoader_C_L1_1 1 // acc_load_unit.sc.h:112 Loop 1.1
#define SCHED_BFP_Acc_WeightLoader_D_L1 2 // acc_load_unit.sc.h:130 Loop 1
#define SCHED_BFP_Acc_WeightLoader_D_L1_1 1 // acc_load_unit.sc.h:132 Loop 1.1
#define SCHED_BFP_Acc_Weight_Transfer_A_L1 1 // acc_load_unit.sc.h:9 Loop 1
#define SCHED_BFP_Acc_Weight_Transfer_B_L1 1 // acc_load_unit.sc.h:24 Loop 1
#define SCHED_BFP_Acc_Weight_Transfer_C_L1 1 // acc_load_unit.sc.h:39 Loop 1
#define SCHED_BFP_Acc_Weight_Transfer_D_L1 1 // acc_load_unit.sc.h:54 Loop 1

#endif

#endif // ACC_SCHEDULE_H
